- cmd/serve.go
- go.mod
- internal/data/models.go
- internal/data/payments.go
- internal/data/payments_test.go
- internal/db/dbtest/dbtest.go
- internal/serve/httphandler/payments_handler.go
- internal/serve/httphandler/payments_handler_test.go
- internal/serve/serve.go
- main.go
Rename the module to follow [Go mod recommendations.](https://go.dev/doc/modules/gomod-ref)
> The module's module path, usually the repository location from which the module can be downloaded by Go tools
Follow the best practices.
N/A
> all: rename module

- go.mod
- internal/data/payments.go
- internal/db/db.go
- internal/serve/serve.go
Use the `fmt` package for error wrapping.
The third-party errors package is unnecessary because we can now use the standard library.
N/A
> all: use fmt for error wrapping

- internal/serve/middleware/middleware_test.go
- internal/services/channel_account_service.go
- internal/services/channel_account_service_test.go
- internal/signing/channel_account_db_signature_client_test.go
- internal/signing/channelaccounts/channel_accounts_model.go
- internal/signing/channelaccounts/channel_accounts_model_test.go
- internal/signing/channelaccounts/encrypter_test.go
- internal/signing/channelaccounts/mocks.go
- internal/signing/env_signature_client_test.go
This PR adds tests for the channel accounts feature
Tech debit.
N/A
> all: channel accounts tests

- go.mod
- internal/serve/httphandler/account_handler.go
- internal/serve/httphandler/account_handler_test.go
- internal/serve/httphandler/payment_handler.go
- internal/serve/httphandler/payment_handler_test.go
- internal/serve/httphandler/request_params_validator.go
- internal/serve/serve.go
- internal/services/account_service.go
- internal/services/account_service_test.go
- internal/services/payment_service.go
- internal/services/payment_service_test.go
- Renames `POST /payments/subscribe` to `POST /accounts/{address}`;
- Renames `POST /payments/unsubscribe` to `DELETE /accounts/{address}`;
These endpoints not only add an account for payments tracking by the ingestion service, but also starts sponsoring their transactions on `POST /tx/create-fee-bump` from that point on. The new route names are therefore more adequate.
N/A
[[Wallet Backend] Rename /payments/(un)subscribe endpoints](https://app.asana.com/0/1202672669313222/1207656913249561/f)
> serve: account registration endpoints renamed

- internal/serve/httphandler/account_handler.go
Sets the status header explicitly to 200 when not using `httpjson.Render`.
Header is not set by default.
N/A
N/A
> serve: write status header for no body responses

- internal/serve/httphandler/account_handler_test.go
- internal/serve/httphandler/payment_handler.go
- internal/serve/httphandler/payment_handler_test.go
- internal/validators/validate.go
- internal/validators/validate_test.go
Adds a cap of 200 to the `limit` parameter of the `GET /payments` endpoint.
So that unreasonably high limits are not allowed which could drain too many resources of the app.
N/A
[[Wallet Backend] Add a limit to the page size parameter in GET /payments](https://app.asana.com/0/1202672669313222/1208148132244616/f)
> httphandler: limit param on payments capped at 200

- internal/entities/rpc.go
- internal/ingest/ingest.go
- internal/services/ingest.go
- internal/services/ingest_test.go
- internal/services/rpc_service.go
- internal/services/rpc_service_test.go
- internal/tss/types.go
- internal/tss/types_test.go
- internal/tss/utils/transaction_service.go
- internal/tss/utils/transaction_service_test.go
- internal/utils/http_client.go
Creates a new RPC service, extracting the logic from the TSS package into a more general one to be available and used across the application.
The `Ingest Service` for the new Balances Ingestion feature will also require RPC communication, therefore the RPC functions are being extracted into its own service. 
N/A
[[Wallet Backend] Refactor RPC code into a separate service](https://app.asana.com/0/1202672669313222/1208409334251161/f)
> services: rpc service

- cmd/ingest.go
- cmd/utils/global_options.go
Adds a new `RPC_URL` environment variable to the `ingest` command.
It was previously not being read from the envs.
N/A
N/A
> cmd: rpc url env added to ingest cmd

- internal/entities/rpc.go
- internal/services/ingest.go
Making sure that the RPC changes listed in protocol 22: https://gist.github.com/Shaptic/6d5c76c5fe2b29e42d1d190241110281 are reflected in the wallet backend
Ensuring that the latest RPC build does not break the wallet backend
N/A
https://github.com/orgs/stellar/projects/58/views/2?filterQuery=&sliceBy%5Bvalue%5D=In+progress&pane=issue&itemId=84956784&issue=stellar%7Cwallet-backend%7C64
> all: Accounting for protocol 22 related RPC changes

- internal/services/ingest_test.go
Closes #81 
Add test for ingest of path payments
Current test cases only cover regular payments
N/A
#81
> [services][feat] #81: Add test for ingesting path payments

- internal/ingest/ingest.go
- internal/serve/serve.go
- internal/services/channel_account_service.go
- internal/services/channel_account_service_test.go
- internal/services/ingest.go
- internal/services/ingest_test.go
- internal/services/mocks.go
- internal/services/rpc_service.go
- internal/services/rpc_service_test.go
- Currently, the code for tracking RPC health is duplicated across both the ingest server and the api server (when creating the channel accounts). This PR organises the RPC heartbeat tracking in a central location and simplifies its design.
- Updated tests accordingly.
The current solution for tracking rpc health was not a simple one and had some code duplication which are resolved in this PR.
NA
Closes #105
> Centralize RPC health monitoring

- README.md
- internal/serve/httphandler/tss_handler.go
- internal/serve/httphandler/tss_handler_test.go
Closes #100 
Makes `GetTransaction` return a `TSSResponse` to match the webhook response.
To move towards a unified response type.
N/A
https://github.com/stellar/wallet-backend/issues/100
> [INTERNAL] /transaction/{transactionhash} returns TSSResponse

- cmd/integrationtests.go
- internal/integrationtests/helpers.go
- internal/integrationtests/integrationtests.go
- internal/serve/httphandler/account_handler.go
- internal/tss/services/transaction_service.go
- internal/tss/services/transaction_service_test.go
- internal/tss/utils/operation_builder.go
- internal/tss/utils/operation_builder_test.go
- pkg/wbclient/client.go
- pkg/wbclient/types/types.go
- scripts/exclude_from_coverage.sh
Update integration tests to include a call to the fee bump endpoint.
Also, assert that the buildTx and the feeBumpTx endpoints have the correct source account and signer.
As part of #149 
The steps to be added are:
> integrationtests: Include call to the fee bump endpoint

- go.mod
- go.sum
- internal/integrationtests/fixtures.go
- internal/integrationtests/helpers.go
- internal/integrationtests/integrationtests.go
- internal/integrationtests/utils.go
- pkg/wbclient/client.go
Update integration tests to submit the transaction to the RPC and poll the RPC waiting for a successful response.
As part of #149
The steps to be added are:
> integrationtests: submit tx to RPC and poll from RPC

- internal/services/rpc_service.go
Fixes the error handling in the GetAccountLedgerSequence function to correctly wrap ErrAccountNotFound, allowing proper error detection in the account sponsorship flow.
Currently, when creating a sponsored account via /tx/create-sponsored-account, the process fails because the error wrapping is incorrect. The error check errors.Is(err, ErrAccountNotFound) fails since the error is returned as a plain string. This fix ensures the error is properly wrapped, allowing correct handling of missing accounts.
N/A
Fixes: [rpc: Fix error wrapping chain in GetAccountLedgerSequence #136](https://github.com/stellar/wallet-backend/issues/136)
Priority: High
> rpc: Fix error wrapping chain in GetAccountLedgerSequence #136

- internal/tss/channels/error_jitter_channel.go
- internal/tss/channels/rpc_caller_channel.go
- internal/tss/channels/webhook_channel.go
- internal/tss/services/transaction_manager.go
Replace `%e` verb with `%w`.
`%e` is a formatting verb used to format floating-point numbers in scientific notation, while errors use `%w` when wrapped or `%v` when logged.
> channels: fix usage of the `%e` verb by replacing it with `%w`

- internal/ingest/ingest.go
- internal/integrationtests/integrationtests.go
- internal/serve/serve.go
- internal/services/channel_account_service.go
- internal/services/channel_account_service_test.go
- internal/services/ingest.go
- internal/services/ingest_test.go
- internal/services/mocks.go
- internal/services/rpc_service.go
- internal/services/rpc_service_test.go
- internal/utils/utils_test.go
Upgrade the ingestor triggers, so it can catch up to the latest ledger, if outdated.
The ingestor was depending oin the health check, that happens every ~5s, which is about the same period of the consensus. This means that if the service got downtime, it would never catch up to the latest ledger.
> services: fix ingestor not catching-up

- internal/services/channel_account_service.go
- internal/services/channel_account_service_test.go
- internal/services/mocks.go
- internal/signing/mocks.go
- internal/signing/store/mocks.go
Channel accounts are now created with sponsored reserves.
Channel accounts should have zero balance.
Closes #175
> services: channel accounts are now created using sponsored reserves and balance=0

- .github/actions/docker-publish/action.yaml
Add `docker/setup-buildx-action` step to the GitHub action, so it cab build to multiple platforms.
Docker publishing job couldn't build multiplatform without adding [Buildx](https://github.com/docker/buildx)
> bugfix: Docker publishing job couldn't build multiplatform

- cmd/channel_account.go
- cmd/ingest.go
- cmd/integrationtests.go
- internal/ingest/ingest.go
- internal/serve/serve.go
- internal/services/ingest.go
- internal/services/ingest_test.go
- internal/services/mocks.go
- internal/services/rpc_service.go
- internal/services/rpc_service_test.go
- internal/signing/store/channel_accounts_model.go
- internal/signing/store/channel_accounts_model_test.go
- internal/signing/store/mocks.go
- internal/signing/store/types.go
- internal/tss/channels/webhook_channel.go
- internal/tss/channels/webhook_channel_test.go
- internal/utils/sql.go
- internal/utils/sql_test.go
Eagerly unlock channel accounts when their txHash is ingested.
So channel accounts became available sooner.
> {ingestor, store}: eagerly unlock channel accounts when their txHash is ingested

- internal/services/rpc_service.go
- internal/services/rpc_service_test.go
Fix test that was failing intermittently due to a timeout that was too short.
The test had a context with timeout of 5 seconds, exactly the same timeout as the one used in the RPC health checker.
> fix: test was failing intermittently due to a timeout that was too short

- internal/data/accounts.go
- internal/data/accounts_test.go
- internal/data/models.go
- internal/data/transactions.go
- internal/data/transactions_test.go
- internal/services/ingest.go
Persist in the database the indexed transactions that pertain to at least one of our watched account(s).
Closes #202
> services: ingest transactions pertaining to at least one of our watched account(s)

- internal/indexer/indexer_buffer.go
- internal/indexer/indexer_buffer_test.go
- internal/services/ingest.go
- internal/services/ingest_test.go
- internal/signing/store/channel_accounts_model.go
- internal/signing/store/channel_accounts_model_test.go
- internal/signing/store/mocks.go
- internal/signing/store/types.go
Eagerly unlock channel accounts when their txHash is observed.
We're replaying #180 now that the ingestor is being reimplemented to index & ingest state changes
Closes #216
> services: eagerly unlock channel accounts when their txHash is observed

- internal/validators/validate.go
- internal/validators/validate_test.go
Allow `POST /accounts{address}` to accept Contract addresses
SO we can support C-accounts
> validators: allow `POST /accounts{address}` to accept Contract addresses

- internal/data/statechanges.go
- internal/data/statechanges_test.go
- internal/db/migrations/2025-06-10.4-create_indexer_table_state_changes.sql
- internal/indexer/indexer.go
- internal/indexer/indexer_buffer.go
- internal/indexer/indexer_buffer_test.go
- internal/indexer/indexer_test.go
- internal/indexer/mocks.go
- internal/indexer/processors/effects.go
- internal/indexer/processors/processors_test_utils.go
- internal/indexer/processors/state_change_builder.go
- internal/indexer/processors/token_transfer.go
- internal/indexer/types/types.go
Use a composite key tuple of transaction/operation order (toid) and the state change order within an operation as the primary key for a state change.
- Adds a new db column:`toID` which represents the operationID if not a fee state change otherwise its a transactionID. This is because fee state changes are not associated with an operation but a tx. The [toID](https://pkg.go.dev/github.com/stellar/go/toid) is an ID that represents the ledger, a transaction's order within that ledger and an operation's order within that tx
- Adds a new column: `StateChangeOrder` which represents the order of a state change within an operation.
- Establishes a deterministic order of state changes within an operation based on a sort key: `toID > category > reason > account ID > .....`.
- Add the primary key …
> Use a composite key as primary key for state changes

- cmd/ingest.go
- cmd/utils/global_options.go
- internal/ingest/ingest.go
- internal/services/ingest.go
- internal/services/ingest_test.go
Allow hosts to configure the limit for the `getLedgers` call
In production, limits above `10` will trigger a timeout on the RPC server if it's using the default RPC configuration of `MAX_GET_LEDGERS_EXECUTION_DURATION="5s"`
> cmd: allow hosts to configure the limit for the `getLedgers` call

- internal/services/ingest.go
- internal/services/rpc_service.go
- internal/services/rpc_service_test.go
- internal/utils/mocks.go
Only call the ingestor's manualTriggerChannel if it's empty
When the processing time takes longer than 5s, which is common in production, since even downloading the ledgers from the RPC takes ~5s for 10 ledgers, the code was entering a deadlock.
Considering the processing time is 11s, here's the sequence of events that lead to a deadlock:
- [**T=0s**] RPC Health Check: channel now contains 1 health update
https://github.com/stellar/wallet-backend/blob/8a12000c478e72169413ef2b47085415b5c1fdb7/internal/services/rpc_service.go#L284
- [**T=0s**] Ingestion Loop Starts. Channel will be emptied and the processing step will take 11s
https://github.com/stellar/wallet-backend/blob/8a12000c478e72169413ef2b47085415b5c1fdb7/internal/services/ingest.go#L226
- [**T=5s**] RPC Health Check (BLOCKS!): RPC …
> Bugfix: race condition caused by processing taking too long

- cmd/channel_account.go
- internal/serve/serve.go
- internal/services/channel_account_service.go
- internal/services/channel_account_service_test.go
- internal/signing/store/channel_accounts_model.go
- internal/signing/store/channel_accounts_model_test.go
- internal/signing/store/mocks.go
- internal/signing/store/types.go
Complete the channel account service, so it can create/delete any number of accounts.
Before this change, it wouldn't be able to delete any accounts and would only be able to create at most 19 accounts. Such behavior is not enough for a prod-ready application.
> services: complete the channel account service so it can create/delete any number of accounts
